language: perl

perl:
- '5.8'
- '5.10'
- '5.12'
- '5.14'
- '5.16'
- '5.18'
- '5.20'
- '5.20'
- '5.24'
- '5.26'

before_install:
- 'sudo apt-get install mecab libmecab-dev mecab-ipadic mecab-ipadic-utf8'

notifications:
  email: false
  slack:
    secure: CVCcYOmQ5oPW2kqnhVA/dkMxL6n2roPUqj/d4ujSTDxHgtB+mln3ws87oLCixQ6HqC3ruP7Iy4o5AytkKAY8vIX8q93ykhBGt1r4VWUhZriTOVr35SOS8zDOGFekOpgTaKKBDiFU58AWQ04HL1gdu1FGtrf572IuXT4EQbn0ZhjZ9H8MwyZIxssSs89XxwdZ9LchL/upAOFc55JEMrwWZRiPVfvcDL0ZYBD5CIK3rXLSTgFFPdZe4xiO/bNyRAmlDEsolzU2zP15j04xLNc7zCvBA92xZfWeriKh3wqkxNteRzKvkOdG7dyPPKThMLUA9YWE42I1t8ZaOhKNGKuHhouaPdsROGiESpyzmm1YTg6+Iv5Y04xWUXe+9EVYC2sdEkGXU37i8fMMDSh/3CvP85tahV5EnM8uw1KFXzSP23Xt1589gLZQvRFpe5lOqOwiRc9ZUI8UYZMhzB+KLhafrHF4F/ZDOVz29+c5Y+VTMQynyI4S+WVYO2KmqH8XS+8u7Ro8HnXWDLHhPbp1FgbdKD31L/rkiiwwQobFuxiMAHVkwCzdSHJdd/1ADHcymYO1ArZUST9ngLrmaZoXmpfBRv+HeoRKz4FcCgc6IanPlVjImXL1n0EFMfwKU09um9d3fX89gnqRbF0DZxnVj8A2yRjL99ADxojnnNheifCtNGI=
